---
- name: update apt repository
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: update apt repository
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

- name: mern app
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - mern-app

- name: install and configure nginx server
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - nginx
